### ISSUE TITLE
Assess ability to do certain pv2 checks (priority = medium)

### ISSUE THREAD

**Issue by sterobin** [pwright/pview#2]
(Reporting on behalf of Ben Hardesty)

@pwright We wonder if pview does (or if not, can do) any other error checks beyond vanilla asciidoctor. Check for things that asciidoctor wouldn't flag, but which would be an issue for Pv2, such as anchor IDs, abstract tagging, etc. That way not only does running the preview give you the rendering, but also allows you to kind of pre-test things that would/will fail in Pantheon2. I suppose this is more of a very-nice-to-have, so if it's not terribly difficult, would be amazing. If it requires more time, then may be a solid RFE.

**Comment by bhardesty** [comment]
Just for context, I tried pview with a Pantheon 1 title, and pview generated the HTML without issue. I'm not sure that this is desirable. The Pantheon 1 title has nested assemblies and other markup that would be invalid in Pantheon 2. As a writer, the biggest value I see from something like pview is the ability to validate that the content is actually valid in Pantheon 2. That would save a huge amount of time, because today, the only way to do such validation is to trial-and-error upload your content to Pantheon 2, adjust as needed, and repeat.

**Comment by pwright** [comment]
@bhardesty  Yes, I think it needs to be clear that the scope of pview is to check table and code example layouts. 
I mentioned to @sterobin  that all I did was package stuff.. I wasn't being modest, the scope of pview is to provide a mechanism to use P2 styles, and that's it! No more features...

However, I know that validation is a common requirement for all sorts of tech writing, so I kicked off https://www.npmjs.com/package/@techwriter/pmodel to address that. The scope of pmodel is much wider, ie to process a set of files and report on the structure of those files (I'm as interested in image alt text as I am in abstracts). It's just a start, but check it out.

**Comment by sterobin** [comment]
@pwright You wonderful, wonderful man you! Just tried out pmodel and it's fantastic. Not what it does exactly, but what purpose it serves and what it can do. Love it.

@bhardesty is on leave, but I'll close this comment and I recommend any further discussion be continued in the pmodel repo.

@bhardesty Once you're back from leave, if you disagree and want to keep this going here, feel free to reopen.
